services:
  database:
    container_name: "postgres-dev"
    image: "postgres:16.6"
    env_file:
      - ../.env.development
    ports:
      - "5432:5432"
  mailcatcher:
    container_name: "mailcatcher-dev"
    image: "sj26/mailcatcher:latest"
    ports:
      - 1025:1025
      - 1080:1080
